### ISSUE TITLE
Adding only a host in a new data source does strange things

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#114]
I was testing the required fields for Data Sources, and I only entered something in the hosting entity field. When I hit add, it added a blank data source (did not save my hosting field content), and immediately switched into edit mode on that new item. If I hit save, it said I had to fill out at least one field (good). If I hit cancel, it saved the completely blank item.

Update: the same thing happens with the Publication title field. Additionally, if only one field is entered, the items display a red "/" at the beginning of each item.

Even more strangeness: I left the empty items in the Data and Pubs list, and ended up switching back and forth between tabs a lot testing something else. All the Data Sources stopped displaying altogether (it still lists three sources, which should be 2 populated and 1 empty), and the blank Pubs entry disappeared (both in the count and in the display) - but not right away.

**Comment by troddick** [comment]
I fixed the 1st two issues here: 
weirdness with adding only hosting entity (for data) and title (for pub).
fixed the weird red / at the beginning.
- couldn't get the issue with switching back and forth and data or pubs disappearing... maybe the first 2 fixes fixed this as well.
