### ISSUE TITLE
Duplicate site action works, but also opens up a blank site form

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#120]
When I use the "duplicate site" icon, it takes me to an empty create site form, although the form isn't quite right (the parameter lists aren't accessible, it's missing the cancel button, and things just look off - more like one of the older versions of the site form).

However, it does duplicate the site correctly, and if you click on the "sites" nav button, it will take you back to the site list which includes the new duplicated site.

**Comment by troddick** [comment]
Fixed.
