### ISSUE TITLE
Site Parameters display issues

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/SiGLDMS#141]
Site Parameters not displayed consistently between the sites view and the site edit page.

**Comment by HansVraga** [comment]
(Notes from Jen)

> This is related to Hans' earlier bug, but I just wanted to document the behavior again since, during the user test, we weren't sure whether it was a genuine information duplication issue or just a display issue. Here's what I wrote down...
> 
> Duplicate site isn't passing original sites visible parameters to edit screen
> Duplicate site is adding an end date that wasn't on the original site
> End date and parameters changing or not duplicating correctly (or at all) from original site

**Comment by troddick** [comment]
all fixed. some testing needed by users to confirm
