### ISSUE TITLE
Two awkward behaviors of the date picker

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#142]
Not sure if you can do anything about this, but...

Many people will just know a date and month, and it would be nice if the selector would auto-select the 1st of the month. It kind of looks like the 1st is selected (it's a darker gray than the rest of the dates), but it isn't actually selected, which is misleading. And if you don't pick anything and hit ok, it just returns to you to the date field without accepting your new date, but doesn't tell you that, so if you're not paying attention, you might not notice that it didn't change it.

Also, when selecting another year, it looks like it preserves the month and day that's already chosen at first, but it really doesn't, so in actuality, you have to start with the year first, then pick the month, then be sure you pick the day. And again, no warning that you haven't selected a new/valid date.

I know that I've seen other calendaring functions that do both of these behaviors, so I'm hoping that this one can be modified to be a little more intuitive.

**Comment by HansVraga** [comment]
Can we consider the date pickers in STN for this?

**Comment by troddick** [comment]
Changed to type="date" input: restricts other characters, allows for tabbing through month, then day then year, with up/down arrow to change values.
Removed buttons in calendar part to reduce confusion. Date must be picked. The library set it up to have light gray on 1st when month is changes just to show a date should be chosen.
