### ISSUE TITLE
Way to either separate terms or error when user enters a comma in the keyword field?

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#143]
During the user test, I noticed that Molly assumed putting a comma between two terms would separate them into two keywords. Is there a way to...
- ask the user if they want to separate the terms
- maybe prevent commas or semi-colons from being used in the field (I'd say prevent all punctuation, but we probably need slashes, dashes, apostrophes, etc.)

I'd be open to other suggestions about helping prevent this mistake if you've got them.

**Comment by troddick** [comment]
I'm not sure if restricting certain characters is a good way to go. I think this is a matter of user training. The field where they input the keyword says as a placeholder "Enter one keyword at a time" and an Add button.

**Comment by jlbruce** [comment]
Ok. I guess we can just keep watch on this field and see if other users have trouble separating terms.
