### ISSUE TITLE
Clicking away from the "Contacts" tab prompts an error

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#144]
Even if you haven't changed anything, trying to click to another tab from the "Contacts" tab gives the error message:

sigldev.wim.usgs.gov says:
Are you sure you want to change tabs? Any unsaved information will be lost.

**Comment by troddick** [comment]
working on getting new version of ngMask which is causing form to be dirty (phone number mask). commented on their github page that their fix did not get pushed into their dist js file. waiting to hear back.

**Comment by troddick** [comment]
fixed.
