### ISSUE TITLE
User test suggestion: indicate changed fields after site duplication

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#145]
Not sure this would be possible, but one of our users suggested that after duplicating a site, during the initial edit, it would be nice to be able to keep track of what fields you had changed. I'm assuming this could look something like:

When opening the site for the first time after duplicating, as you start editing fields, those with new or changed information are highlighted in some way (outline, different background color in the field, etc.). But once you hit save, and that info gets written to the database, it looses its "duplicate" status and becomes a normal site.

I'm assuming this would need to be a special editing state, which is good because we'd need to do some special labeling and instructions at the top so they know this behavior is a one-time thing.

(This is not at all a core feature that needs to happen, just a wishlish item for the future.)

**Comment by troddick** [comment]
Still a wishlist item with the newly added MSE? @jlbruce

**Comment by jlbruce** [comment]
Again, betting not. Table for now.

**Comment by troddick** [comment]
Closing for now. Reopen if desired later.
