### ISSUE TITLE
Fix browser pop-up when wrong password entered on login

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/SiGLDMS#147]
(IIS setting in services likely culprit)
<img width="1031" alt="iispasswordpop-up" src="https://cloud.githubusercontent.com/assets/12058013/15229313/6f8fb0b0-185e-11e6-9095-110d6ae467de.PNG">

**Comment by troddick** [comment]
once we go live, s3 has necessary setting for this to not happen. also need to check setting on services in toad.
