### ISSUE TITLE
Cancelling out of a new project leaves you in an unfinished project screen

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#153]
If you start a new project, and then hit Cancel, it leaves you in a empty project. You can't select any of the other tabs, but the "Publish to SiGL" button is interactive (doesn't actually work). I don't think it actually DID create an empty project, but it looks like it might have, which could be scary to new users. Any way that Cancel could take you back to the Home page?

**Comment by troddick** [comment]
Yes. Done.
