### ISSUE TITLE
Suggested feature: Ability to hide columns

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#156]
It would be great to be able to hide columns from view. If possible, this could be done through a check-box drop-down menu above the table in the upper right. All columns would default on, but could be unchecked and hid from view. It would be great if those settings could be saved for an entire user session.

An even better option would be for each user to be able to set their preferred default column view in their user settings, but could always locally override that within an individual project.

**Comment by troddick** [comment]
Is this still an interest in having, since we now have the MSE? @jlbruce

**Comment by jlbruce** [comment]
I'm betting not. Let's table until we see how the MSE is received.

**Comment by troddick** [comment]
Closing for now. Reopen if desired later.
