### ISSUE TITLE
Newly added Data Sources and Publications won't display after switching tabs

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#162]
After creating a Data Source or Pub, it shows up in the display area until you switch tabs. After that, the lists won't display until you add another new Data Source or Pub, and then both will show up and be editable again until you move off to another tab.

If you exit out of the project and return, all the previous items will display, even as you move to different tabs. However, if you add a new item, then move off the tab and return, the items from the previous editing session will show, but not the current one.

For example, add Pub 1. Move to contacts, come back, nothing shows. Add Pub 2. Both Pub 1 and 2 appear. Move to contacts, come back, nothing shows. Go back to project list. Come back to this project, go to pubs, Pubs 1 and 2 show up. Add Pub 3. All show up. Move to contacts, come back, Pubs 1 and 2 show up, Pub 3 does not.

**Comment by troddick** [comment]
Fixed by adding a new service that stores and retrieves (get/set) project things rather than relying on calling the SiGLServices or based on what was passed initially.
