### ISSUE TITLE
Style request - move save/cancel buttons below edited item for Data Sources, Contacts, and Pubs

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#163]
Now that we're doing a lot more of the "you must hit save" actions, most of the save/cancel buttons are at the bottom (the traditional place). However, when editing Data Sources, Contacts, and Pubs, they're above the item that's being edited, which is a little confusing. (Now that I've been out of the system for a while, I had to look for them and was momentarily confused.) Can we move them below the item without too much effort?

**Comment by troddick** [comment]
done.
