### ISSUE TITLE
Some duplication display issues

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#168]
It was hard for me to thoroughly test the duplication function since there were a couple of fields that I could edit without bombing (unfortunately the same fields with duplication issues), but I did see some repetition and order display issues...

Check the Resource Component and Sampling Frequency columns - the second site as duplicates listed (2 estuaries, 2 semi-annuals), and then the third and fourth sites have the same selections, but they display in a different order, making it hard for them to be quickly proofed.

![duplication_displayorder](https://cloud.githubusercontent.com/assets/16122136/17605132/84e970a0-5fde-11e6-9750-b34e7e232e28.PNG)

Once we get the editing thing fixed I can do a more controlled duplication and editing process to narrow down what's going on.

**Comment by troddick** [comment]
Did this double resources (Estuary) appear just after only doing a duplicate? or did you duplicate successfully and the double resources appeared after editing the duplicated site?

**Comment by jlbruce** [comment]
I'm not sure - with all the bombing associated with those fields it was hard to remember when it happened. Now that you've hopefully fixed that issue I'll do a more controlled testing and let you know.

**Comment by jlbruce** [comment]
Hmm. I can't seem to reproduce these display issues, and I've tested multiple rounds of duplication and editing. It is possible something else you did fixed it? Whatever the reason, I think we're ok for now. I'll tell Molly to keep an eye out for it (she's got some projects to enter once we've pushed to Prod).
