### ISSUE TITLE
Shortened parameter names for multi-site editing

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#171]
I've shortened the parameter names to reduce the amount of space needed for the headers. You can find them [here](https://docs.google.com/a/doi.gov/spreadsheets/d/1zIJnRMNUehhlTcNygygIHNoVUSdYS3WWTWjqA6uYmu4/edit?usp=sharing).

Hopefully we can still use the full name in the header rollover.

**Comment by troddick** [comment]
Header rollover is a pro feature. Not available in the free version.

**Comment by troddick** [comment]
Changed to full names.
