### ISSUE TITLE
Validation glitch when using ending dates

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#173]
If you've entered a start date, and you manually enter an end date (using numbers, not the calendar picker), the validation kicks in after you type the first digit of the year, causing it to error out before you can enter the full year. For example, trying to type in Aug 16, 2016, it only accepts "08/16/0002", and the year 0002 is always going to be before anything in the past two centuries, so it yells and clears the field. This happens both for the project and sampling end date fields.

**Comment by troddick** [comment]
fixed

**Comment by troddick** [comment]
done for sites..

**Comment by troddick** [comment]
done for projects.
