### ISSUE TITLE
uploader spreadsheet modifications

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/SiGLDMS#174]
Jen,
When you update the spreadsheet's parameters (putting a . where not selected (x) ), can you also change the dropdown choice for Country to be "United States Of America" instead of what it is currently "United States". This will match what the site expects. 

Thanks

**Comment by jlbruce** [comment]
Actually, could we change the database to be "United States" instead? That's how the USGS says it, and I was planning on changing it when I got access to edit the picklists anyway.

**Comment by troddick** [comment]
Will do.
