### ISSUE TITLE
Prod DMS - Contacts not showing up for ScienceBase projects

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#176]
I was checking the content of some projects imported from ScienceBase (with the data manger name: ScienceBaseLName, ScienceBaseFName). It looks like they have contacts assigned (the tab shows a positive count, usually 2 or 3), but when I click on the Contacts tab, it's empty. I was actually checking how the contacts got imported, so it may be that the error is in the imported data, not in the display.

**Comment by troddick** [comment]
You are correct. The contact data did not have a required phone number, which the client expected. I removed the expectation of the phone and now it displays properly.
