### ISSUE TITLE
Add new project field to DB and DMS: Monitoring Coordination

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/SiGLDMS#178]
detailed here:
https://docs.google.com/document/d/1bp4AiobSBcJCvKud1RkXeN8qTzCn0uieb9Og7qiPJ-Q/edit

**Comment by jlbruce** [comment]
I talked to John Walker yesterday, and he thinks this will be an important field to search and display on soon. At the minimum, we'll need to be able to start collecting it in the DMS when the Lake Ontario start entering content this fall. He'd like to see it incorporated for a demo to them by mid-Nov.

**Comment by troddick** [comment]
@jlbruce 
Functionality exists in sigldev version. Test it and let me know when ready to make it live. ( along with the project created and last_updated stamps now visible .. both these updates will go live at the same time.

**Comment by jlbruce** [comment]
Looks and works great! Just a few text changes:

Change field title to say: "Monitoring Coordination Effort"

Change help text to say:
"Use this field to associate your project with specific monitoring efforts and groups."

**Comment by troddick** [comment]
Done
