### ISSUE TITLE
Multi-site editing: more accurate validation for lat/long

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#179]
Can we restrict the lat/long validation to more accurate values?
Lat: positive decimal number between 22 and 55
Long: negative decimal number between -130 and -55

Also, can we change the validation error messages:
"Latitude must be between 22.0 and 55.0 (NAD83 digital degrees)."
"Longitude must be between -130.0 and -55.0 (NAD83 digital degrees)."

**Comment by troddick** [comment]
Done. And I think I may have improved the removal of the invalid flag I was setting and removing when they make a mistake and then fix it. Hopefully this will fix some of the other validation issues.
