### ISSUE TITLE
Multi-site editing (MSE): lat/long validation won't clear (and sometimes deletes all sites?)

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#180]
I was testing to see what would happen in case someone tried to enter a ddmmss lat by entering "44 55 66" (with spaces). The validation was unhappy (expectedly), but I couldn't get the error to clear, and somehow it ended up removing the other two sites that I had successfully entered. I reset (which got the rows back) and tried to recreate that error (unsuccessfully), but I did continue to have issues with the validation. Once the bad values are fully deleted, it still continues to hold the validation error, even if there are no other values in the row. This prevents the user from saving the document. The only way I was able to clear the error was by deleting the row entirely, but this would be bad if the user had actual good, unsaved data in this row or other rows.

**Comment by troddick** [comment]
May have fixed the weirdness with the validation errors hanging around.
As far as dec. deg. vs ddmmss, maybe we should add that to the popup that shows the validation error. Right now it just states "Latitude must be between 22.0 and 55.0 (NAD83 digital degrees)." Should that be (NAD83 decimal degrees)??

**Comment by jlbruce** [comment]
Good catch! Yes, it should definitely say "decimal degrees", not "digital degrees".
