### ISSUE TITLE
MSE: awkward error resolution in cells with dropdowns/pop-ups

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#181]
I was testing copy and pasting some data from the excel template, and the MSE gave some validation errors because the capitalization in the spreadsheet didn't match the DMS. While the capitalization is a separate issue, it was really confusing to deal with the validation error because it would complain, and I'd say ok, and then it would bring up the check box list, where I'd enter the values I wanted, but then it wouldn't delete the incorrect ones, so it would error again once I accepted the new ones. It would add them, but again, it would throw the error over and over until I clicked twice into the cell and manually deleted them. I'm a little worried that people won't know to click twice to get into the editing mode in drop-down cells.

Can we have it that, when an validation error occurs in a cell where the value is pre-formmatted (dates, dropdowns, and pop-ups), and the user selects an acceptable value, the original error values are cleared from the cell and overwritten with the new pop-up selections?

**Comment by troddick** [comment]
Done.
