### ISSUE TITLE
MSE: clearing open cell contents

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#182]
Building on my previous issue for clearing pre-formatted cells... Clearing information from cells with validation is a little tricky, because you have to know to click twice to access the content of the cell to clear it. I like having the double-click editing option, because once you know it's there it's really fast, but I also feel like we need another solution to help those that won't know to try the double-click.

I noticed that when you right click, you get options to add/delete rows. Does the editor know when you're clicked on a row vs. a single cell? If so, we could display the existing options when they've got an entire row highlighted, BUT when someone is clicked on a single cell, could we have the right-click menu show options of copy, paste, and clear the cell contents?

Additionally, the validation error often won't clear when you've deleted the content completely (for example, in the site name field of an empty row), and the only way to get rid of the error is to delete the row entirely.

**Comment by troddick** [comment]
Regarding the validation errors not going away after deleting a site name when the rest of the row is empty -- I fixed that. I now check to see if that row has any other values. If so, the validation is thrown, otherwise, it doesn't go into the validation error.

**Comment by troddick** [comment]
Also, in regards to double-clicking to edit -  I could add something to the error message that comes up. Error ...whatever it says now... Please double-click the cell to edit it's contents.. or something to that effect?
