### ISSUE TITLE
MSE: date field not validating

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#183]
The start date field let me manually type "aug 3, 2011" without forcing me to use the "08/11/2011" format. It didn't draw the red cell error, but it also wouldn't let me save it (but again, didn't highlight the cell as problematic after throwing the invalid error, so the user doesn't know where the problem is).

**Comment by troddick** [comment]
Fixed. Automatically converts pasted dates into proper format.
