### ISSUE TITLE
MSE: Changes to reset and cancel buttons

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#185]
Can we relabel the reset button to say "Revert", and if the user clicks it, can we have a pop-up that says "Warning! This will revert the site table to the last saved version. All current edits will be lost." with "OK" and "Cancel" options.

Also, an we have a pop-up warning on the Cancel that says "Warning! Any edits will be lost." with "OK" and "Cancel" options.

**Comment by troddick** [comment]
Done.
