### ISSUE TITLE
MSE: spreadsheet and DMS picklists have different capitalization

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#186]
The spreadsheet and DMS picklist terms have different capitalizations, which is causing validation errors when copy and pasting. Either the MSE needs to ignore capitalization on dropdown/pop-up cells, or we need to get the two products in sync. I've had more curation control over the spreadsheet, so I'd prefer to use that as the master list. I'm happy to do the editing on this using the DMS admin settings, if that would be more efficient and less troublesome, but I'm assuming we'd need to update both the prod and test lists? Let me know how I can best help with this.

**Comment by troddick** [comment]
Picklists have been updated to match the spreadsheet. Only a few were affected.

**Resources**
from Groundwater to Ground water
**Media**
from Animal Tissue to Animal tissue
from Plant Tissue to Plant tissue
from Remote Sensing to Remote sensing
from Sediment/Soil to Sediment/soil
**Frequency**
from Semi-monthly to Semi-Monthly
from Semi-weekly to Semi-Weekly

**Comment by jlbruce** [comment]
Eh, crap. I should have looked more closely at the options in the spreadsheet, because those were inconsistent. Sorry to make you change these back - I've fixed them in my spreadsheet.

**Resources**
should be "Groundwater" (one word)

**Frequency**
should be "Semi-monthly" (lower case m)
should be "Semi-weekly" (lower case w)
