### ISSUE TITLE
MSE: custom message for large site upload?

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#189]
Just to see what would happen, I copy and pasted over 700 sites from the spreadsheet into the MSE yesterday. All went well (yay!), but the save, as expected, took a VERY long time. I don't know how long - it had been churning for about 15/20 min before I had to leave for the day, and it hadn't gotten to the part where the progress bar had started displaying individual site completions yet. It did successfully finish while I was away. 

I know you've made a lot of effort to implement visual cues that something is happening during upload, but maybe we need some other kind of message. I was planning on adding a note at the top of the MSE reminding people to save early and often, but maybe it should be expanded to warn people about large site batches. Or maybe, if the system can tell that a bunch of new sites have been added, we could do a pop-up on Save that says something like "Saves with over X new sites will quite a while to complete. Please do not interrupt the save process or data may be lost."

Recommendations or thoughts?

**Comment by troddick** [comment]
I am already using the count of affected sites (new and updating) to use in the progress bar. I could do a check on that count and if it's higher than a certain number show a modal letting them know it will take a long time.. and maybe give them an OK and cancel button, in case they don't want to deal with that right then?

**Comment by troddick** [comment]
If more than 20 sites are being added/edited, I include a message above the progress bar.
