### ISSUE TITLE
Site dates disappear and reappear when switching tabs, even in editor

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#190]
Discovered by Adam, our Minnesota WSC user, behaviour replicated by Jen

When you first open a project and go to the site list, you can see the sampling start and end dates listed in the site table. But if you switch tabs, and then come back, the dates don't display. However, if you back all the way out to the project list and then come back into the project again, the dates are there. 

But the really creepy thing is that, if you do the switching-tab no-display thing, and you open one of the sites up to edit it, the date DOESN'T display in the editing window either. But if you back out and come in again, and the date displays fine in the table, it also displays in the editing window. (I can't remember a time when the editing window didn't display the actual info in the database.)

**Comment by troddick** [comment]
Great catch! Took me a little digging to find the culprit! But I got 'em and fixed it.
