### ISSUE TITLE
Adding project edit dates to DMS views

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#192]
Since we're now capturing the first created and last updated dates for each project, can they be listed some where in the DMS view? Maybe in the project view, in the blank space underneath the tabs on the left column?

Also, can you add "Last updated" date as an sortable column to the Home project listing, as the right-most column?

**Comment by troddick** [comment]
@jlbruce , this reminds me. Did we make a decision on what date to use for all the projects that are in there now? Since they were added pre- created_timestamp and last_editedStamp creation.
Also, if you want the last updated to be a sortable column, should it be stamped when created to put something in there..then updated with all future edits?

**Comment by troddick** [comment]
I've updated testing so you can see the last updated date as sortable, and created: and last updated: dates on under the tabs on the left. The last updated date gets updated as things are added/removed/edited on the project. 
Once we get the created date straightened out on all existing projects, I'll push this live and close this issue.

**Comment by jlbruce** [comment]
Thanks, Tonia! This looks GREAT!

As for what to do with those projects without Creation Dates, is it OK to leave them empty? Will that screw up the system? I feel like giving them some random creation date would be misleading, so if we can go without it, that'd be best.

But, as a follow up to that, if there are some that I do want to manually assign (in the past year, there were two rounds of new project entry that I can probably track down easily, and since they were really recent, it'd be nice for those to have dates). If that's possible, let me know what info you'd need and how best to format it to be most efficient for you.

As for filling out the Last Edited field, yes, as new projects are created, then that date should be assigned as the Last Edited until another modification is made and the date is updated. Just like above for older projects (assuming it's ok to leave them blank), we'll leave the Last Edited date blank too. (Although, again, for those recent projects, I'd like to assign the Creation Date also as the Last Edited date, if possible.)

**Comment by jlbruce** [comment]
One question though - I edited a project (just the basic project info - I was testing the new Monitoring Coordination field), and the Last Edited date didn't update until after I'd closed it (the new date showed up in the project listing), and was correct when I reopened it. Any way we could get the dates to refresh while you're still working in the project?

**Comment by troddick** [comment]
All done. Did I send you an excel sheet of projects for you to add the create_date and Monitoring coordination to? I can create the script from that spreadsheet whenever you have time to fill it out and send it back.
Thanks
