### ISSUE TITLE
MSE: switching from manual entry to multi-edits

### ISSUE THREAD

**Issue by mbreitmun** [USGS-WiM/SiGLDMS#193]
I entered a site manually and saved it successfully. Then, within the same project, I chose multi-edits and copy-pasted in from the MSE spreadsheet (from sites I previously successfully entered and saved from a different test). They paste and look fine. When I try to save I get "Error updating site 0 of [X]" message. I tried different sites and different numbers of sites, but keep on getting an error. 

This is my first github post -if I'm missing anything etiquette or otherwise -let me know!
-Molly

![manualentry_thenmultiedit](https://cloud.githubusercontent.com/assets/22300964/18650583/708d5498-7e8b-11e6-8626-673ba752f736.JPG)

**Comment by mbreitmun** [comment]
After exiting to the Home page after a few save attempts, I selected the project again from the project name list: each site that I entered had actually been saved, so instead of the 4 I originally intended, 8 sites total were saved with my multiple attempts of copy and pasting more individual sites.

**Comment by troddick** [comment]
I'm not sure. I encountered this once, while debugging and saw the same error. When I tried again to dig in to see how I can fix the code, I couldn't recreate the issue. I copied 4 sites from the MSE and pasted them at the bottom and it all saved just fine. 
Strange. I will keep this open and try again later.
