### ISSUE TITLE
MSE: duplicate the "create new project" button?

### ISSUE THREAD

**Issue by mbreitmun** [USGS-WiM/SiGLDMS#194]
possibly more user friendly to either locate the "create new project button" at the top of the project list (esp. as the list gets long) or place one at the top and bottom.

**Comment by troddick** [comment]
Jen, response to this. I do agree that the Create new project button at the bottom can be difficult to see with lots of projects. I can add another one at the top or just move it. Let me know.
Thanks.

**Comment by jlbruce** [comment]
I agree. Let's move the button to the top. There's only a few managers with a long list of projects, so I don't think the benefits of doing two buttons outweigh the potential confusion/overkill for most users. But moving it to the top will make sure that all managers are aware of it.

**Comment by jlbruce** [comment]
I changed my mind about this, and think that two buttons would be best. Sorry for the indecision!

**Comment by troddick** [comment]
I missed this one. Done.

**Comment by jlbruce** [comment]
Can the "create" buttons be aligned right, and be on the same line as the "Click on a project name..." text? (I'm trying to minimize the amount of wasted white space at the top.) Also, in the button, can you add a little space between the plus sign at the text?

**Comment by troddick** [comment]
Done.
