### ISSUE TITLE
MSE: trouble saving

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#195]
I'm having trouble saving from the MSE today. I'm working in a project with 9 existing sites (so, it shouldn't be a performance load issue). I add one new site (required fields only), hit "Save", and nothing happens. If I hit "Save" again, or hit "Cancel" or "Revert", that seems to trigger the processing screen (with a gray processing bar), but nothing happens. It just sits there spinning, but nothing ever uploads or progresses. The only way to get out of it is to reload the URL, and no information has been saved.

However, if I try to save immediate after opening (without making any changes), I get a BLUE processing bar which also says "redirecting", but again, nothing happens.

**Comment by troddick** [comment]
saving without making any changed.. I fixed this. I didn't have a catch that redirects back to siteList if sites are only being deleted or nothing at all (only worked if editing or creating sites)

save button is working now. Let me know if this glitch happens again for you.
