### ISSUE TITLE
Single-site editing (SSE): interface revisions

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#198]
Make the following changes to the existing single-site page interface (see mock-up below):
- Add header "SITES:" to match other tab headers
- Add toggle button (hopefully similar to the publish toggle, but with labels on each side) for "Single Site Editing" and "Spreadsheet Mode"
- Add text above the table: "Use single-site editing to modify one site at a time. Select spreadsheet mode to edit multiple sites at a time (similar to Excel)."
- Add legend row above table to explain icons (a user suggestion)
- Move "Create New Site" button to right side, and repeat button at bottom of the table.

![singlesite](https://cloud.githubusercontent.com/assets/16122136/19786380/463a236a-9c63-11e6-87ab-2158cba122e3.png)

**Comment by troddick** [comment]
Done.
Done.
Done.
Done.
and...
Done.
