### ISSUE TITLE
MSE: interface revisions

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#199]
Make the following edits to the MSE page:
- Add "SITES:" header (same as other tab headers)
- Add "Single Site Editing"/"Spreadsheet Mode" toggle
- Add text below header (see image below for line breaks):

Spreadsheet mode works much like Excel; each row is an individual site. You can highlight and copy multiple cells or rows, or you can click and drag from the lower right cell corner to populate an entire column. You can also copy and paste directly from the Excel SiGL Site Worksheet.

Right-click any cell to add or remove a row (site). Drag column headers to adjust column widths.

Gray cells cannot be modified. Some cells have data validation applied and will turn red if the value entered does not meet the requirements. Red cells must be resolved before saving. The more sites, the longer the save will take. Please be patient.

_(Ideally, I'd like the "SiGL Site Worksheet" text to be hyperlinked to the SiGL Drupal project, when that becomes available.)_
- Change the right-click message to read "Remove **this** row"
- Reformat buttons to match other site buttons, change order, and modify the colors as marked below.

![multisite](https://cloud.githubusercontent.com/assets/16122136/19786496/d627d648-9c63-11e6-8617-8e1be3982bc3.png)

**Comment by troddick** [comment]
Done
Done
Done
Done
and... 
Done. :)

**Comment by jlbruce** [comment]
Yay! Looks great! Just two small requests...

On the SSE/MSE toggle, the blue rollover state occurs on the site that is already selected (essentially showing the user that they can click on the side that is already active). Instead, when you hover over the gray, inactive state, can that turn blue (and maybe turn teal instead of blue)? So it shows the user that that side can be clicked?

Also, just to be completely idiot-proof - on the MSE view, can you add a little text line on the far right (inline with the toggle) that says "Return to project", which takes them back to the Project Info tab? Just in case they don't know to click on the SSE toggle to get back to the tabbed project view?

**Comment by jlbruce** [comment]
Caught a glitch... if you make an edit to a site, and then click the SSE toggle, it just goes back to SSE mode and you lose your changes. Can you make the SSE toggle check to see if any edits have been made before leaving MSE mode? Or if you can't check, can you alert the user, like the cancel button?

The same request will also apply to the new "Return to project" text, when you get to that. Thanks!

**Comment by troddick** [comment]
I'm going to pull out part of this issue and make a new one to assign to Mitch (in regards to the color of hover and such).
Not going to do the extra text line "Return to project" because I moved the MSE page into the project parent wrapper. (Now the tabs appear to the left, like on the SSE page).
Added a modal asking 'are you sure' when they click to go back to Single Site Edit page.
I will close this. If an issue arises from moving the MSE page, create a new issue. Thanks!

**Comment by jlbruce** [comment]
Overall, great. Definitely don't need the "return to project" anymore.

One little request though... on the new modal, make the cancel orange? (I'm trying to establish a visual language where the teal means yes/accept and orange means warning/cancel/delete, so just in case they don't read the labels, they'll subconsciously see the color and know which button is which.)
