### ISSUE TITLE
MSE: keyboard still active during modal if a cell is selected

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#203]
Related to a previous issue when the spreadsheet could still be accessed while a modal was active - it looks like the mouse-click has been deactivated during the modal, but if a cell is highlighted, the user can still use the keyboard to move around and edit values.

A good example of this is if you enter a positive value in the Longitude field and then move on to the next cell to the right (the Country field). The system throws the error modal, and then you hit return to close it (which doesn't work, but it selects the drop down) and if the user doesn't notice, maybe they hit enter again, which selects Canada (again, maybe with them noticing).

Another example might be some who tries to fix an open-text cell while the modal is still open, but all the enters push them into the new row, and the next, and then they've made a mess that they have to clean up once they've closed the modal.

Is it possible to deselect the cell when the modal appears? As long as a cell isn't selected (which happens as soon as you click anywhere with your mouse), the lock-out seems to work just fine, because you're not allowed to click back into a cell.

**Comment by troddick** [comment]
Fixed. All validation modals trigger remove cursor from inside the table when they open.
