### ISSUE TITLE
MSE: validation save error without any visible errors

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#204]
After repetitively and intentionally causing validation errors in a couple of cells in some empty rows (I was testing the modal lock-out issue), I deleted that content using the "Remove row" functionality. (I thought that would be the most effective way to clear all content - ha!) But, when I went to save, it gave me the modal that I needed to resolve all the errors before saving, but it didn't highlight any problematic cells, and I couldn't see any errors in the existing rows.

On a lark, I copy and pasted content from two good rows into the rows where I had been working, and tried saving again, and it went through without issue. So my guess is the system retained some content in those rows where I was testing even after the "remove row" request, which through the validation error because it thought they were active rows, even though the display had them completely empty?

**Comment by troddick** [comment]
fixed. added afterRemoveRow event to loop through inValids and remove if in selectedRow being removed.
