### ISSUE TITLE
MSE: save error

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#208]
I was testing the cell-deselect-on-modal issue (looks great, btw!), and after fixing my cells, I tried to save the new site. It spun, and the console showed the attached error.

![save_error](https://cloud.githubusercontent.com/assets/16122136/19971522/4964fd22-a1ad-11e6-863a-e0d23244ccad.jpg)

I had to refresh (and lost the site), and entered a new site with only good info in the required fields, and got the same error, although it didn't spin forever. I tried to revert, and it spun again. On refresh again, I had lost the site.

**Comment by troddick** [comment]
fixed.
