### ISSUE TITLE
MSE: show more rows on first open

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#209]
Just a styling request - I noticed with the new embedded MSE version, when you first open a project with no sites, there's only three empty rows, and then a big empty space, and then the save/revert/cancel buttons. Can we fill that space with more empty rows, so people fill more comfortable copy&pasting more than three rows at a time? I know it works (i tested it), but even I was a little dubious when I first tried - Excel has us trained to expect endless empty rows. It looks like you'd need about 12 total rows to fill the space, at least on my monitor.

**Comment by troddick** [comment]
I'm not sure I can wire it up to set the minSpareRows as a condition on if there are no sites in the table or not. I could increase the minSpareRows overall, increasing it from 3 to 12. This will be the case at all times (whether the table is empty --no sites-- or not).
Is that fine?

**Comment by jlbruce** [comment]
That's fine, I think, if the only consequence is a longer scrolling area? People are going to end up scrolling a lot anyway.
