### ISSUE TITLE
MSE/SSE toggle requires a second click

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#213]
From Molly:
Switching between SSE and MSE toggle sometimes requires a second click (it happened 2x, but not I'm trying to recreate it, and it's working smooth). Oh! Not working again...the active toggle turns from orange to turquoise and then requires an additional click to actual switch between modes. And now it's smooth again. Not sure why it's changing. Other than clicking on site fields and then clicking back to the toggles, not performing any new tasks.

**Comment by jlbruce** [comment]
I couldn't replicate this exact behavior, although I did notice that sometimes my MSE button is teal after it's been selected, and sometimes orange (or at least I think it was, but I can't get it back now)? I saw that Mitch had closed the rollover color issue but it doesn't seem to have changed for me even though I've cleared by cache, so maybe something is going with that new code?

**Comment by troddick** [comment]
Mitch fixed all the issues. I needed to pull his code down and update sigldev server. It's all working now.
