### ISSUE TITLE
2 requests on "Project Information" entry page

### ISSUE THREAD

**Issue by mbreitmun** [USGS-WiM/SiGLDMS#221]
1. Some projects I am entering only have a known start year (and no a full month/day/year). Can year-only be made a valid entry? Otherwise, I'm assuming it can't be searched by year in the mapper?

2. Not sure if this is redundant: add "Baseline" or "Baseline Survey" as a project objective. For the projects I'm working on, they seem to fit best under that. "Assessment" might fit, but that seems much more broad.

**Comment by troddick** [comment]
1. The start date is a "Date" format property, which requires a month and date also. If no month/day is known, would choosing 01/01/Year work? 
2. Question for @jlbruce

**Comment by jlbruce** [comment]
1. We've used Jan 1 in the past for other projects without a known start day. Maybe we could add "If you do not know the month/day, please select Jan 1." to the helper text?

2. This is a good suggestion - I've actually wondered if "Assessment" was too general of a term anyway (over half of our projects are tagged with it). I didn't remove Assessment, but I did add "Baseline assessment" as a choice. ("Survey" is a little too specific - you can do other baseline assessments that aren't field surveys.)

**Comment by troddick** [comment]
1. I can add that to the helper text on the Project Start Date.
2. Assuming this is resolved then.

**Comment by jlbruce** [comment]
Can you add this as helper text to all date entries - Project End Date, and Site Start/End Dates? Thank you!
