### ISSUE TITLE
Sites not appearing in Mapper

### ISSUE THREAD

**Issue by mbreitmun** [USGS-WiM/SiGLDMS#226]
The Bad River Watershed Association (BRWA) sites (that I haven't edited since 12/2016) are not appearing on the mapper. I search by org, the page loads saying "224 matching sites," but no points appear on the map. 
![brwa_224sites_not_visible](https://cloud.githubusercontent.com/assets/22300964/23366539/b00d5202-fccc-11e6-90a3-2273f3652c58.JPG)

**Comment by jlbruce** [comment]
Checking in the DMS, there are 6 projects associated with the Bad River Watershed Association, none of which is displaying in the mapper. The sites look fine in the DMS, and the projects are set to publish. We also found another project from another organization entirely "2012 USGS and GLIFWC collaboration" that also isn't displaying in the mapper. Molly is going to check all the other projects she's entered lately to see if there are others with this problem.

To be clear, the projects and sites look fine in the DMS, and they're searchable in the mapper, and the site lists show up in the pop-up, but the points just don't display spatially.

**Comment by mbreitmun** [comment]
These are all the projects I've entered:

Show up spatially on the mapper:
1. Background Inorganic Investigation Project
2. Baseline water quality conditions for the Bad River rivermouth plume in Lake Superior along the Bad River Reservation and Apostle Islands National Lakeshore.
3. Ceded Territory Water Monitoring

Do not show up spatially: 
1. Bad River watershed groundwater model development and pre-mine baseline conditions
2. 2012 USGS and GLIFWC collaboration
3. The Geochemical Landscape of Northwestern Wisconsin and Adjacent Parts of Northern Michigan and Minnesota (Geochemical Data Files)
4. BRWA Volunteer-led macroinvertebate sampling
5. BRWA Volunteer-led water chemistry sampling
6. BRWA E.coli Historic
7. BRWA Staff Macroinvertebrate sampling
8. BRWA Staff Continuous Temperature Monitoring Sites
9. BRWA Staff Total Phosphorus sampling
10.  Penokee Hills Continuous Flow and Temperature Monitoring
