### ISSUE TITLE
Can't access other any tabs in Prod DMS

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#227]
I'm unable to access any of a project's tabs in the DMS. The initial Project Information tab loads fine, but when I click on any other tab, it spins for a while and then throws a 502 bad gateway error (see screenshot). It seems to be happening for any project that I've tried so far. I'm in Chrome for PC, in Prod. Since we're under the gun for a demo tomorrow, I wanted to log this right away, but I'll continue to test to see if it happens on TEST or in other browsers.

**Comment by troddick** [comment]
this was due to s3 being down for a few hours.
