### ISSUE TITLE
adding a project organization

### ISSUE THREAD

**Issue by mbreitmun** [USGS-WiM/SiGLDMS#228]
This project has a bunch of project orgs...I added a bunch from the drop down as well as 'add new' organization. 

I had no prob with first 8 entries. 

adding Great Lakes Indian Fish and Wildlife Commission from the add organization drop down gave me trouble.
![tried_adding_glifwc_from_dropdown](https://cloud.githubusercontent.com/assets/22300964/23911536/228f04e4-08ab-11e7-8fb7-20cb0315d6d1.JPG)

**Comment by mbreitmun** [comment]
(It saved as ",  , ") 

When I exited out of the project and re-entered, GLIFWC does come up in the org list, but then "Biological Serives Division" and "Environmental Section" also come up for GLIFWC -I did not select a division or section here though. 
![glifwc_bsd_es](https://cloud.githubusercontent.com/assets/22300964/23911739/b307bce6-08ab-11e7-8d8c-637c7ee1477d.JPG)

**Comment by mbreitmun** [comment]
I think GLIFWC is the culprit, I deleted it and tried adding it again and am getting the same problem

**Comment by troddick** [comment]
Good catch. There was an issue in the services when posting this new org (there is one in there for the org/div/sec combo, but not just the org alone). It kept finding the one with the div/sec and using that instead and then it just got confused. I fixed it and updated the proj_coop to just have the org without div/sec for your project.
