### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by mbreitmun** [USGS-WiM/SiGLDMS#230]
Hi -I am trying to add USGS as an organization to a new project I'm in the middle of entering. I keep getting an "internal server error" message for this action only (I left and re-entered the project and I'm still not able to save the Org). I'm able to add and save in other fields within this project. 
![internal_server_error](https://cloud.githubusercontent.com/assets/22300964/23965276/77b14088-0985-11e7-8331-5a889ac7064b.JPG)

**Comment by troddick** [comment]
I'm wondering if my wonderful fix yesterday just broke it more. I'll investigate.

**Comment by troddick** [comment]
Yep. That was my fault. I changed something so that I could test yesterday and missed changing it back. All fixed now.
