### ISSUE TITLE
unable to access Org list after visiting Resources

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#232]
I was testing the Org editing (which works really great!!!), and I went over to the Settings > Resources > Resource Component list to check something, and when I came back through Settings to get to the Org list again, it errored out upon requesting the Org list. (see image)

![org_editing](https://cloud.githubusercontent.com/assets/16122136/24162043/350a1332-0e34-11e7-8b5c-cfee075e5e22.PNG)

I tried going back to the Home and coming in again, and that didn't fix it. I cleared my cache, logged out and logged back in, and still get the error. I can't seem to get rid of it. I'm in PC Chrome, if that helps.

**Comment by troddick** [comment]
Fixed.
