### ISSUE TITLE
request: refresh Org list after adding new

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#233]
This is just a convenience request, but when I'm in the Settings > Org list, and I use the "Add new organization" button to add a new Org or Div or Section, can the Org list page refresh when I close the pop-up? I don't think there would be a time when we wouldn't want to confirm that the Org we added did get added successfully, and manually refreshing the page is just an extra step. If it's a big pain, you don't have to bother, but it'd be really nice.

**Comment by troddick** [comment]
The new org/div/section is not showing in the orgList when you close the popup? It should be. I've tested and they are appearing as soon as I close the new org popup.

**Comment by jlbruce** [comment]
This is working fine now. Not sure what the issue was before...
