### ISSUE TITLE
sigltest server

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/SiGLDMS#235]
Need the sigltest server running as soon as possible please.

**Comment by troddick** [comment]
can we just have the sigldev server on for now (since we turned off stnwebtest)? This is being used every day by myself and veni. I've been turning it back on each morning.
Thanks.

**Comment by aaronstephenson** [comment]
I added this instance ID to the auto-start list, so it should now always run during business hours and be shut down automatically outside business hours. If it's working as expected for you, @troddick , please feel free to close this issue. Thanks.
