### ISSUE TITLE
"Public" data manager role - old role that needs to be deleted?

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#236]
I was creating new prod and test accounts for Jim Blount (he's replacing Molly as our SiGL Partner Liaison), and I noticed that there's a manager named Dan Diego who's assigned to the manager role called "Public". Is that a real role (he's the only one who has it)? Is he a real user (there is no Dan Diego with the USGS, at least as of today)? If so, it's causing problems... I tried clicking on his name to see his details, and the page just spun - both in test and prod. I was able to get back to the manager list by refreshing the entire page, but I haven't been able to access his individual record.

**Comment by HansVraga** [comment]
Just so you know @jlbruce - "Dan Diego" is an alias for one of our team - this must be a holdout from development testing from a while back. We should be able to clean this up without much issue.

**Comment by jlbruce** [comment]
I did not know that, hahaha.
Feel free to leave DD in Dev if you'd like, but he made his way to Prod, so probably not ideal to leave him there. It was more the unknown manager role that caught my eye.

**Comment by troddick** [comment]
Dan Diego removed from production.
