### ISSUE TITLE
DMS dev login password change?

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#237]
I tried to log in to the DMS Dev version today with the LAMPADMIN account, and it gave me a 401 Unauthorized error. No worries -- I was able to get in with my personal manager- level account and I didn't need to do anything admin-y -- but I'm thinking maybe someone changed the password? Would a better practice be for me to create personalized admin accounts on both Prod and Dev instead of using the same one you guys use?

**Comment by troddick** [comment]
resolved via chat. a new admin user will be created by Jen for her use moving forward.
