### ISSUE TITLE
create new siglProduction Database

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/SiGLDMS#241]
new PostgreSQL DB that matches the schema of the pgtest DB in wim Sandbox.

DB name: sigl
schema: siglAdmin

we've already pulled the data from the original lamp production DB into pgtest in the sandbox, so data and schema can be migrated to this new production sigl DB.

Once completed please notify Jeremy or Katrin and they will finish the migration.

**Comment by esmyers** [comment]
I'm out of town next week, but Jeremy and I talked and he knows exactly how to do the migration

**Comment by aaronstephenson** [comment]
New RDS DB created in the WIM Production AWS subaccount. Details in the WIM KeePass.
