### ISSUE TITLE
Remediate Vulnerability: Vulnerable Javascript Library

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/SiGLDMS#244]
Acunetix scan reports this app is using jQuery 2.2.4 and should be updated.

**Comment by aaronstephenson** [comment]
This is a "medium" level vulnerability and must be remediated as soon as possible.

**Comment by esmyers** [comment]
updated to v 3.5.1 and deployed to the server.  I removed bower resolutions https://github.com/USGS-WiM/SiGLDMS/commit/77b3b9341948a61fa5102e9d41377c7263660bb0#diff-dedb6c21fdaac9cba4da4afde881ffe5c80f80896274dbf7971d312fc6f5207d and used npm shrinkwrap for graceful-fs 4.2.2 to get the thing working again.
