### ISSUE TITLE
Remediate Vulnerability: Outdated Javascript Library

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/SiGLDMS#247]
Acunetix scan reports this app is using several outdated libraries and should be updated:

- [x] AngularJS 1.4.7

- [x] Bootstrap 3.3.7

- [x] Rickshaw 1.1.1

**Comment by aaronstephenson** [comment]
This is an "info" level vulnerability, so no rush to remediate it right now.

**Comment by esmyers** [comment]
went to the last version of bootstrap 3, but going to 4 (or 5) will likely cause breaking changes and a dependency nightmare.

Couldn't find Rickshaw in the tree.  Maybe my latest updates of top-level dependencies have taken care of the problem

**Comment by aaronstephenson** [comment]
Closing because we can ignore "info" level vulnerabilities.
