### ISSUE TITLE
Remediate Vulnerability: Password field submitted using GET method

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/SiGLDMS#253]
Acunetix scan reports this app uses GET to submit passwords. Passwords must be submitted using a POST request. This is a Medium vulnerability and is a priority.

**Comment by esmyers** [comment]
I definitely changed this last year and it is using a POST.  Do you think it's the response methods that are causing the issue?  
![image](https://user-images.githubusercontent.com/2495167/138122906-9a032e22-f2f4-4b75-b420-054dfe447285.png)

**Comment by esmyers** [comment]
Do we have a specific URL that was identified by the Acunetix scan?  

There is an old test version of the DMS running in that bucket that uses the GET method.  I deleted that application, but I'm trying to determine if there is still an issue with the current updated version of sigl.wim.usgs.gov/SiGLDMS/

**Comment by aaronstephenson** [comment]
It says it's hitting https://sigl.wim.usgs.gov/SiGLDMS/component/logInOut/login.html

Here's the specific section of the scan report:

![image](https://user-images.githubusercontent.com/8713712/138131364-dea2fc04-11c1-4876-b37f-ca8459456bd2.png)

**Comment by aaronstephenson** [comment]
You're probably right about the headers. This line is interesting:
>The form's method attribute is either set to GET, or not defined at all,
in which case it defaults to GET

So yeah, maybe it's the values in the `Access-Control-Allow-Methods` header?

**Comment by esmyers** [comment]
This should take care of it https://github.com/USGS-WiM/SiGLDMS/pull/254   

- All that really needs to happen to disable the GET is to set the html `<form  method="post">`    (login.html line: 13)   
- I also set the header defaults to POST in the controller  (line 80, never mind all the automatic formatting changes)
- As a result you'll get a 405 forbidden error if you type your creds directly into https://sigl.wim.usgs.gov/SiGLDMS/component/logInOut/login.html and try to submit

I have no way of testing that this is an acceptable fix for them, but based on the outline of the problem, this seems to have fixed the issue to the best of my knowledge.

**Comment by aaronstephenson** [comment]
Thanks @esmyers, I'm sure this will fix it. We'll know for sure during the next scan in December!
