### ISSUE TITLE
Edit Project -- URL and Keyword 

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/SiGLDMS#42]
'Changed some date information before creating the project. It saved the date info, but deleted the fixed URL I had just entered, and it also didn’t save the keyword I had entered before I started trying to save it.' -- copy/pasted comment from Jen

**Comment by jlbruce** [comment]
I couldn't replicate this exact trouble, but in general, when creating a project, it's doing a good job of forcing errors to be fixed without deleting the other information that's added or edited between responding to the errors.

The same can't be said about editing, which isn't consistently enforcing or applying if new or edited fields are saved when other errors exist. I've documented this in another issue, so you can probably archive this one.

**Comment by troddick** [comment]
With the addition of the project modal for creating and editing, I'm going to call this closed. 
If a new issue arises while testing the new Project create/edit modal, lets open a new issue, for the sake of cleanliness.
