### ISSUE TITLE
Multi-Select Picklists (CSS)

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/SiGLDMS#43]
The multi-select picklists aren’t displaying like the single picklists... the options are all spread out and it’s really hard to scan the list quickly (or check what you’ve got selected). It would be great if they could be narrower.
Also, is it possible to make the selected options in the multi-select picklists stronger? The gray fill and little check mark is so subtle. It looks a lot different that the rest of the styling, so I’m not sure how much control you have, but maybe selected options could have a orange rule and bold orange text (a bit of a mix between the keyword and parameters styling)?

**Comment by troddick** [comment]
Also, if a lot of Objectives are entered, the list runs past the white box into the space below. If the list is REALLY long, it goes under the fields below and continues on. It also switches to be displayed centered instead of justified left, which looks out of place. When the list is short, it’s fine (the field actually shrinks to fit). Look at “Birds as Indicators…” for an example project.

**Comment by jlbruce** [comment]
This is much improved now after Mitch's styling upgrades. My only request would before the field label to be at the top of the list, not the bottom. (For example, in project "modal edit project", the field label "Project Objectives" doesn't show up until the last item is listed ("Non-Regulatory"). This also happens for the keyword and website fields.
