### ISSUE TITLE
datepickers (CSS)

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/SiGLDMS#46]
The pop-up calendars aren’t displaying right. The weeks seem to be numbered (strange), but there isn’t a month or year label or selector. And the selection buttons at the bottom are being forced into date circles, so you can’t read the labels. There also doesn’t seem to be any way to scroll through months right or left. Aesthetically, the dark gray numbers on the orange are really hard to read. I’d suggest doing the circles in the dark taupe, and then use white and black numbers for the current and surrounding months, respectively. Maybe the current date circle could be teal and the selected date could be orange, if possible. (Same problems for Sites calendars)

**Comment by mitchas** [comment]
Working on this right now. Having a hard time finding the classes to style, but I think I'm getting it.

**Comment by jlbruce** [comment]
These work great now. Thanks!
