### ISSUE TITLE
Site List loading lag for lots of sites

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/SiGLDMS#57]
Site list loading performance is an issue. Projects between 50 and 200 take a while, but eventually come up. (We might need a stronger waiting message.) But over 200, and they don’t (maybe I’m not being patient enough, but I went off and did other things, and they still hadn’t loaded). Plus, when you try to go back, most of the time continues to hang, so you can’t get out. Sometimes even closing the window and opening the main URL doesn’t even help - you have to quit out of the browser, relaunch, and login again.

**Comment by troddick** [comment]
Will look into making a SiteListView to see if this speeds up retrieval.

**Comment by jlbruce** [comment]
This has greatly improved!!! The over-200 sites took a little bit of time to load, but nothing outside of what a user would expect. Even the 6,000+ site list loaded, although that took a few minutes, but I'm fine with asking users to wait that long. Whatever you did, it worked great!
