### ISSUE TITLE
Site List (CSS)

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/SiGLDMS#58]
The site listing has some issues, mostly display-related, which are causing the table to be somewhat ineffective. Ideally, people could review multiple sites at once for comparison and troubleshooting, but right now, you aren’t able to view many sites or columns in the existing view. Here are some potential suggestions, but I’m also open to other ideas you might have:
- Can the site table window be larger? It’s inset a lot more than the other tabs, and I feel like there’s a lot of wasted space along the edges (esp since maximizing the table is ideal).
- Can the “Create Site” button not be so scrunched up in the corner (add a little padding on the top and left)?
- The header row and site info font could be a bit smaller to help fit more columns.
- Any way to incorporate very light gray lines to define the sides of the columns?
- Any way to keep the first row (site name) locked in place while you scroll over to the right, so you’ll always know which site you’re looking at regardless of where you are in the table?
- In the same vein, any way to lock the header row AND a scroll bar at the top? For long site lists, they’ll need to scroll in areas without seeing the bottom, and they’ll want to know what the column label is. (I know that you can click into the table and scroll, but most people won’t intuitively try that.) - Would it help to have the up/down scrolling be contained in the site window?

So, the parameters are making each site row really deep, which is precluding the usefulness of seeing all the sites in table form. Can we do one or more of the following…
- Widen that individual column so it can fit more parameters wide (Do you have control over column widths? They seem to change, and I couldn’t figure out what their rules were.)
- Split the parameters list into 5 columns, one for each group (ideal, I think))
- Leave off the parameter list altogether (last resort)
  - Jen

**Comment by troddick** [comment]
I could not assign more than one person as the assignee.. 
I feel this could be a joint effort between Mitch and I. I could use some help on styling this.
Mitch has said he is looking into locking the first 3 columns.
-T

**Comment by jlbruce** [comment]
I know this is a long list of suggestions, and they don't need to all be incorporated by the Beta. But it would be great to get it looking a little better than it does now, so pick some things that are (relatively) easy to implement, and then we'll continue improving it as we go on.
