### ISSUE TITLE
Project list sort order 

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/SiGLDMS#78]
Any way to preserve your project listing sort settings if you go into a project and then come back out? For admins, it’s a pain to have it keep resetting.

For example, if I sort projects by site count, then go into a project, then come back to the list, it's reverted back to sorting by project name. Although resetting the ascending/descending order would be confusing, too. Hopefully it would either be able to save all the settings (column and order), or none at all.

**Comment by troddick** [comment]
look into storing sortingOrder and checking for value onload..

**Comment by troddick** [comment]
done.

**Comment by jlbruce** [comment]
This isn't working for me, at least in Firefox. The default sort is now Z to A, and if I resort and then go into a project, when I come back out, it's back to Z to A.

**Comment by troddick** [comment]
So strange. I swear this was working. I tested all over the place. But, now it's not. lol..
I found the issue. string 'true' does not equal boolean true .. fixed.
