### ISSUE TITLE
Chrome not clearing DMS login credentials

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#88]
When I went to test the DMS today (many, many days after I was last logged in and after at least one cache clearing and two full computer restarts), I tried to access the main URL: http://sigldev.wim.usgs.gov/SiGL_DMS/#!/
Instead of taking me to the login screen, it kept redirecting to: http://sigldev.wim.usgs.gov/SiGL_DMS/#/projects
where it just spun and spun as it tried to load. I couldn't log out, I couldn't get it to redirect to a more basic part of the URL. Eventually, after a few minutes, it finally loaded the project list, but when I tried to go into a project, again, it just spun and spun.

Firefox didn't seem to have this issue, as it had forgotten my credentials and took me to the normal login screen. And I was likely last logged into Firefox around the same time as Chrome, as I remember one of the last things I tested before the GLEC demo was if Tonia's new credentialing updates were working, which I tested in both browsers.

**Comment by troddick** [comment]
I tested this by setting an expiration date of 1 min. Logged in, went to a project, then closed the browser and waiting 2 minutes. When I ran it again, it sent me to the login page. 

Please test this once more for me. I'm wondering if maybe you changed your password? I did not update that code to apply the expiration on the auth cookie when I set it upon changing a password. I have fixed that part.

**Comment by jlbruce** [comment]
Update: while I can't test the multi-day delay, I can tell you that Chrome kept my credentials through a browser restart (both an immediate restart and after waiting about 15 after close), and through a full computer restart. However, it took me back to wherever I last was (either within a project or the project list), and functioned normally - no spinning or redirecting.

If I cleared my cache manually, it did forget them and ask me to log back in.

**Comment by troddick** [comment]
Try this one more time. I changed the way the property is being stored with the expiration date on the credentials.

**Comment by jlbruce** [comment]
I retested credentials clearing in Chrome and Firefox, and both saved the credentials through closing the tab, closing the browser, logging out of my Windows account, and a hard restart of my computer. They did time out after some period of inactivity (I left them overnight).

The one other thing I tested - I was able to log into the Lampadmin account from both my desktop and my laptop at the same time. I don't know how prevalent shared accounts will be, but it is possible to have multiple computers logged into the same account at the same time. I'm assuming that's probably not good.
