### ISSUE TITLE
Adding a project website throws an error

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#90]
When editing a project, and you go to add a new website, it gives an modal error that says “Please populate all required fields” and gives the "Project not saved" toaster, even though there is no other required information missing (Name, duration, and status are all filled out).

For some projects, the website saves regardless (and when it does save, sometimes it throws both the error and the "project saved" toaster, sometimes just the red modal/toaster pair). And sometimes it looks like it saves (the website gets added to the list area), but when you back out of the project, they disappear. (See project "Test - another effort to break things!" - the first website was added during creation (no error messages), the second was added even though it through an error, and then two others looked like they got added but were gone when I came back in.

For other projects, it doesn't save the new website at all. (See project "Test Project Alpha")

**Comment by troddick** [comment]
adding project modal instead of save onBlur resolves this issue.
