### ISSUE TITLE
Sites are having trouble creating and then loading

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#91]
I tried to create two sites:
The first one, I tried to enter as many errors as possible, and then after those were finally resolved through all the errors, when I went to save, it just spun and spun. When I backed out to the project list by editing the URL, and then came back into the project, 1 site was listed, but when I tried to go to that tab, it just spun and spun again, never loading.

I went to another project and added another site, this one initially entered correctly the first time, and the green "Site created" toaster came up, but still, it spun and spun. I had to back out again using the URL, and again, when I came back into the project, it had 1 site listed, but when clicking on the site tab, the list never came up (so much spinning).

Editing a site went just fine.

**Comment by troddick** [comment]
created a site create modal. Hopefully resolved this issue.
