### ISSUE TITLE
Clearing required fields during editing causes confusing messages

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#92]
After creating a project with the required fields, I went back and cleared them by selecting the empty top row in the drop down. It gave me an error, but then let me fill out other parts of the project form. 

For keywords and objectives, it let me add them freely, with green toasters. No errors. These fields did actually save.

For the rest of the project fields, it still looked like it let me add them, but it threw the red modal and toaster, but then still saved them. For the open text fields, it left the Save button visible, as if it hadn't saved yet. Clicking back and forth to other tabs saved the information, so it looked like it saved, but when I back to the project list and came back in, all my work in these fields had been lost. This is very misleading.

Additionally, after the red modal/toasters, it highlighted the field using the dashed line, but didn't have the white balloon message underneath like it does during project duration. What's the difference between the red glow and the dashed line/balloon highlights?

**Comment by troddick** [comment]
Lots here. I think most are fixed due to changing the project create/edit a modal. Please test to ensure, but I'm going to close this and if a new modal-related issue comes up, just open a new issue.
