### ISSUE TITLE
Site editing: hitting enter returns you to site list, but doesn't save

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGLDMS#94]
In the project editing mode, most of those fields are either action based (which trigger a save), or have save or add buttons at the end. In site editing mode, there are a few fields with short open text, and they don't have a submit button. Hitting enter, which often is a proxy for submit, returns you to the site list without saving the information. It even spins a little, which feels like it's saving, but it isn't. We either need to allow hitting enter to act as a save (ideal), or add action buttons at the end to remind the user to save their edits.

This would apply to Name, Waterbody, Platform, and URL.

**Comment by troddick** [comment]
fixed.
